- hosts: collectors
  tasks:
    - name: Running the Container
      docker_container:
        image: fx8350:5000/dht22:latest
        name: dht22
        state: started
        privileged: yes
        restart_policy: always
        force_kill: yes
        pull: yes
        hostname: "{{ ansible_hostname }}"
